### ISSUE TITLE
have a --color=always param to be able to keep colors when using pipe

### ISSUE THREAD

**Issue by Thatkookooguy** [stephencelis/ghi#243]
right now when I use `ghi show 2 -- <project_name> | sed ****`

The color output of ghi is discard since it isn't outputting to TTY.

Maybe add a --color=always flag like less or grep so it will force ghi to keep colors even if not outputted directly to a TTY?

**Comment by AlexChesters** [comment]
This seems sensible @Thatkookooguy, thanks!. If you or anyone else feels like implementing this and opening a PR it would be well-received!

**Comment by mrnfrancesco** [comment]
Since this (very old) requested feature was already satisfied by `--[no-]color` option, could I suggest to close this issue?

`ghi --color list -- stephencelis/ghi | less -mR` is an example of this feature working (note the `-mR` on `less` to show colorized output instead of raw color escapes printed out)
