### ISSUE TITLE
Milestone name inferred from branch prefix.

### ISSUE THREAD

**Issue by jmalloc** [stephencelis/ghi#289]
Please let me know if I'm using this incorrectly - but it seems like there's an issue with the milestone subcommand whereby it uses the branch prefix (ie, issue number) as the milestone name.

```console
$ ghi --version
ghi version 1.1.1

$ git branch | grep '*'
* 112-retain-strand-result

$ ghi milestone --list
(Inferring issue from branch prefix: #112)
Not Found
```

**Comment by AlexChesters** [comment]
Hi there!

I don't believe this is an issue, `ghi` interacts with `milestones` by their number, rather than the milestone name.

E.g.:
```
ghi list --milestone
# AlexChesters/.emacs.d open milestones
  1: Version 1.0.0 
```
You would then add that milestone to issue 4 in the following way:
`ghi edit 4 -M 1'

**Comment by jmalloc** [comment]
The `milestone` command when the `master` branch is checked out, but if the current branch name starts with a number and hyphen I get the error from my example above.

**Comment by caifara** [comment]
I second that `ghi milestone -l` should list milestones whatever the current inferred issue.

There is this other issue: https://github.com/stephencelis/ghi/issues/198 which is a similar pain in my opinion (it's closed because one can opt out of inferring through a config option, but that's not really a good solution as inferring is really powerful).

I would state that there are two kinds of interesting commands, let's call them global commands (like `ghi milestone -l` and `ghi new -m ""`) and local commands (like `ghi show`). Global commands should (imho) ignore the current working branch whereas local commands should always try to infer the issue number.

**Comment by shubhamshuklaer** [comment]
@jmalloc @caifara 
For this issue check out this version
https://raw.githubusercontent.com/shubhamshuklaer/ghi/289_issue_inferring_not_found/ghi
and reply whether it fixes the issue.

**Comment by caifara** [comment]
@shubhamshuklaer but but … I want to use the PR version too … ;-) Thx! (https://github.com/stephencelis/ghi/pull/288)
