### ISSUE TITLE
Support milestones that are not integers

### ISSUE THREAD

**Issue by matchstick** [stephencelis/ghi#316]
It looks like the "ghi list -M <milestone>" flag only works when the milestone is a number. For some repos the milestone can be a string.  I am not a ruby expert but that is what I am inferring from: 

https://github.com/stephencelis/ghi/blob/master/lib/ghi/commands/list.rb#L82

Is there any way we can match on a string as some repos use strings as a milestone?

**Comment by AlexChesters** [comment]
Hi @matchstick,

`ghi` works with all milestones regardless of the name. Rather than using the name of the milestone, `ghi` uses the number assigned to that milestone by GitHub. It's the equivalent of associating with issues by their number rather than their title.

I realise this can be confusing, #311 is an issue which would hopefully make this easier to understand. Thanks!
